vote:
  repository: "quackusarle/vote"
  tag: "14"
  replicaCount: 1

  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "250m"
  service:
    type: ClusterIP
    port: 80
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: 80

result:
  repository: "quackusarle/result"
  tag: "25"
  replicaCount: 1
  
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "250m"
      
  service:
    type: ClusterIP
    port: 80
    
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: 80

worker:
  repository: "quackusarle/worker"
  tag: "4"
  replicaCount: 1
  
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "250m"
      
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: 80

redis:
  image:
    repository: "redis"
    tag: "alpine"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379

db:
  image:
    repository: "postgres"
    tag: "15-alpine"
  replicaCount: 1
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
  service:
    type: ClusterIP
    port: 5432